name = "gilded-payment-api"
main = "src/index.js"
compatibility_date = "2026-08-24"

[vars]
ALLOWED_ORIGIN = "https://recon.pages.dev"

[[kv_namespaces]]
binding = "GILDED_KV"
id = "64e45acd88a44488aee5bf39ffcc2a6a"
